### ISSUE TITLE
[Question] Input folder

### ISSUE THREAD

**Issue by RoyZengTW** [gibahjoe/openapi-generator-dart#109]
### Description of the bug

Hello,
I have multiple yaml file. 
Could I input a folder instead a yaml file ?

Thanks

### Steps to reproduce

N/A

### Expected behavior

Input a folder to the generator

### Platform

Linux

### Library version

4.12.0

### Flutter version

3.10.6

### Flutter channel

stable

**Comment by MincDev** [comment]
Was there a solution to this?

**Comment by RoyZengTW** [comment]
I finally use [openapi-merge-cli](https://www.npmjs.com/package/openapi-merge-cli) to merge all the file into one.
