### ISSUE TITLE
Nullable should default to true

### ISSUE THREAD

**Issue by darkfrog26** [gibahjoe/openapi-generator-dart#118]
### Description of the bug

In the OpenAPI spec, the `nullable` property is optional, but the values should default to not being nullable if the value is not set. However, I end up with all nullable values with this comment:
```
  ///
  /// Please note: This property should have been non-nullable! Since the specification file
  /// does not include a default value (using the "default:" property), however, the generated
  /// source code must fall back to having a nullable type.
  /// Consider adding a "default:" property in the specification file to hide this note.
  ///
```
I don't want to specify a default value, the value must be specified though.

### Steps to reproduce

Define an OpenAPI property without `nullable` being set.

### Expected behavior

Default to final value set in the constructor.

### Platform

Linux

### Library version

master

### Flutter version

doesn't matter

### Flutter channel

stable

**Comment by gibahjoe** [comment]
Is the openapi spec you are trying to generate version 3.1? I suspect this might be the issue as the last supported version by the library (before the 5.0 release) was version 3.0

**Comment by darkfrog26** [comment]
Version `3.0.3`

**Comment by gibahjoe** [comment]
Please share reproducible minimal spec

**Comment by darkfrog26** [comment]
I went ahead and created my own Dart generator for OpenAPI, I'll close this.
