### ISSUE TITLE
Invalid model generated via List in additional properties

### ISSUE THREAD

**Issue by ricardoboss** [gibahjoe/openapi-generator-dart#137]
### Description of the bug

When using a spec that defines a schema of an object containing string keys and string array values the generator produces invalid Dart code.

### Steps to reproduce

To reproduce, create a new flutter project and set up `openapi_generator` with the following spec:

```json
{
  "openapi": "3.0.1",
  "info": {
    "title": "Test API",
    "version": "1.0"
  },
  "paths": {
    "/Test": {
      "get": {
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/TestDto"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "TestDto": {
        "required": [
          "values"
        ],
        "type": "object",
        "properties": {
          "values": {
            "type": "object",
            "additionalProperties": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        },
        "additionalProperties": false
      }
    }
  }
}
```

### Expected behavior

The generated code should be able to compile.

The code should have the following differences:

```diff
        return TestDto(
          values: json[r'values'] == null
              ? const {}
-             : mapCastOfType<String, List>(json, r'values'),
+             : mapCastOfType<String, List<String>>(json, r'values') ?? {},
        );
```

### Screenshots

<img width="1004" alt="image" src="https://github.com/gibahjoe/openapi-generator-dart/assets/6266356/447c9032-f63d-4542-ae5d-81c3d26a7f7e">

### Platform

macOS

### Library version

5.0.2

### Flutter version

3.16.9

### Flutter channel

stable

**Comment by gibahjoe** [comment]
Hi, This seems to be an issue with the official openapi generator. I am able to reproduce it even with the latest official version released. You will have better luck raising the issue there. Please reopen this issue if you disagree.

**Comment by ricardoboss** [comment]
Yeah I guess they are tracking that issue with this one https://github.com/OpenAPITools/openapi-generator/issues/8179
