### ISSUE TITLE
feature or documentation request

### ISSUE THREAD

**Issue by dgaedcke** [gibahjoe/openapi-generator-dart#138]
### Description of the bug

I'm a bit confused ... does this package allow me to decorate my router (shelf) endpoints and generate OpenAPI specs directly off my actual server API  (types in and out) ?  Or must I do a bunch of manual input to mirror the actual router configuration?  I'm wanting a library that uses my actual API endpoint code to determine what the OpenAPI contract entails.
I've used apispec (https://apispec.readthedocs.io/en/latest/) with Python to achieve similar code-gen.  Can or do you support this approach?

### Steps to reproduce

Can't find answer in existing docs

### Expected behavior

need more docs

### Platform

macOS

### Library version

10.7.6

### Flutter version

3.2

### Flutter channel

stable

### Additional context

```text
Does this package allow me to decorate my router (shelf) endpoints and generate OpenAPI specs directly off my actual server API  (types in and out) ?  Or must I do a bunch of manual input to mirror the actual router configuration?  I'm wanting a library that uses my actual API endpoint code to determine what the OpenAPI contract entails.
I've used apispec (https://apispec.readthedocs.io/en/latest/) with Python to achieve similar code-gen.  Can or do you support this approach?
```

**Comment by Nexushunter** [comment]
At the moment, this library generates from an OAS spec. 

I definitely like the idea of having annotations that would that. I think that would be better implemented once we have [macros](https://dart.dev/language/macros). Currently, it appears that would be possible post [Q1](https://dart.dev/language/macros#timeline) 2025.

**Comment by gibahjoe** [comment]
Hi! Just to clarify, as @Nexushunter mentioned, this library is designed to generate a **client SDK** based on an existing OpenAPI specification. However, it does not generate the OpenAPI specification itself.

Currently, there isn't a Dart library that can automatically generate OpenAPI specifications. However, if you're using Java, you might find [springdoc](https://springdoc.org/) helpful, as it can generate OpenAPI specifications for you.

Hope this helps!

**Comment by dgaedcke** [comment]
There are a few, but I'm not sure which are stable / reliable:
https://pub.dev/packages/openapi_spec
https://pub.dev/packages/shelf_open_api
https://pub.dev/packages/shelf_open_api_generator
