### ISSUE TITLE
Add option to disable caching

### ISSUE THREAD

**Issue by ricardoboss** [gibahjoe/openapi-generator-dart#144]
### Description of the bug

I have a file locally available and don't want the generator to cache it. I cannot disable this behaviour.

### Steps to reproduce

-

### Expected behavior

-

### Platform

iOS

### Library version

5.0.2

### Flutter version

3.19.4

### Flutter channel

stable

**Comment by philitell** [comment]
Is there a way of force generation without changing anything in the source file?

**Comment by gibahjoe** [comment]
Unfortunately as far as I know, there is no way.
