### ISSUE TITLE
v1.1.X has dependencies that are incompatible with current flutter version

### ISSUE THREAD

**Issue by dividebyzero** [gibahjoe/openapi-generator-dart#16]
running pub get gives me errors
"Because every version of flutter from sdk depends on meta 1.1.8 and generic_reader >=0.1.1 depends on meta ^1.2.2, flutter from sdk is incompatible with generic_reader >=0.1.1.
And because openapi_generator >=1.1.0 depends on generic_reader ^0.1.5, flutter from sdk is incompatible with openapi_generator >=1.1.0."

switching to 1.0.8 resolves it. what do you need generic_reader ^0.1.5 for ? is it possible to switch to lower version ?

**Comment by gibahjoe** [comment]
Hi. Version 1.11 introduced using enums for more type safety. Generic reader is a library that is used to read the enum values during source gen.

Anyway, I expected flutter sdk to have updated by now but since it's taking them a while, I will look into alternatives. Thanks

**Comment by gibahjoe** [comment]
Flutter sdk has been updated. This should no longer be an issue. Closing for now.
