### ISSUE TITLE
Expected Identifier Error

### ISSUE THREAD

**Issue by niklaskolloge** [gibahjoe/openapi-generator-dart#18]
Hi, 

I get the following error here: 

[INFO] Running build...
[INFO] Generating SDK summary...
[SEVERE] openapi_generator:openapi_generator on lib/ApiConfiguration.dart:

Bad state: Unexpected diagnostics:
C:\flutter\bin\cache\dart-sdk\lib\core\uri.dart:3259:39 - Expected an identifier.
[INFO] Running build completed, took 820ms

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 49ms

Could you help me out? 

Thanks!

**Comment by robertcsakany** [comment]
I had similar issues, when I clean flutter dart cachce directories, run pub get and generation build everything become fine.

**Comment by gibahjoe** [comment]
@niklaskolloge ,

This looks like its not an error specific to this library. Closing this for now.
