### ISSUE TITLE
Syntax error in generated code

### ISSUE THREAD

**Issue by markbeij** [gibahjoe/openapi-generator-dart#23]
I'm currently experiencing a problem with the generator as the code that is produced can not be build.
I have narrowed it down to the following:

swagger definition:
```javascript
{
    "swagger": "2.0",
    "info": {
      "version": "1.0",
      "title": "FooBar"
    },
    "host": "foo.bar.com",
    "basePath": "/dev",
    "tags": [

    ],
    "paths": {
    },
    "securityDefinitions": {
    },
    "definitions": {
      "GeocodedWaypoint": {
        "type": "object",
        "properties": {
          "geocoderStatus": {
            "type": "string",
            "enum": [
              "OK",
              "ZERO_RESULTS"
            ]
          },
          "partialMatch": {
            "type": "boolean"
          },
          "placeId": {
            "type": "string"
          },
          "types": {
            "type": "array",
            "items": {
              "type": "string",
              "enum": [
                "STREET_ADDRESS",
                "STREET_NUMBER"
              ]
            }
          }
        },
        "title": "GeocodedWaypoint"
      }
    }
  }
```

It produces a class `GeocodedWaypoint` with the following property:
`GeocodedWaypointTypesEnum types = GeocodedWaypointTypesEnum.[];`

* generatorName: Generator.DART2_API
* openapi_generator: ^1.1.3
* openapi_generator_annotations: ^1.0.8
* Command: `flutter pub run build_runner build --delete-conflicting-outputs`

**Comment by markbeij** [comment]
Also here's the output from flutter doctor
[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-NL)
    • Flutter version 1.22.4 at /Users/mbeij/DEV/flutter
    • Framework revision 1aafb3a8b9 (4 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/mbeij/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.8.4

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

**Comment by gibahjoe** [comment]
Hello @markbeij , this seems to be an issue with the dart2 generator. This library is just a wrapper around the openapi generator libraries.

Here is the dart2 library repo where you should create an issue. https://github.com/dart-ogurets/dart-openapi-maven/issues

Meanwhile, you could try the dio generator. It works well without problems.

Closing this for now. Let me know if you need further assistance

**Comment by gibahjoe** [comment]
You can track this issue here

https://github.com/dart-ogurets/dart-openapi-maven/issues/19
