### ISSUE TITLE
Package generation does not support null-safety

### ISSUE THREAD

**Issue by harsimranmaan** [gibahjoe/openapi-generator-dart#26]
Relates #24

**Comment by gibahjoe** [comment]
Hi,

Thank you for raising an issue. There is a null safety version already existing `2.0.0-nullsafety.0`
If you are in a hurry, you can use that without the ^ so that it doesn't fetch 2.0.0 instead.

I am working on updating it.

Happy holidays.

**Comment by gibahjoe** [comment]
Versions `3.0.0-nullsafety.1` have been published

Let me know if you have any issues

Regards

**Comment by harsimranmaan** [comment]
Sorry I meant, null safety for generated packages and not the package itself

**Comment by harsimranmaan** [comment]
I am not in a rush. This can wait as I have plenty on plate to upgrade other dependencies. But at some point, it would be nice to have null-safety support for the generated sdk.
