### ISSUE TITLE
Dart1 support has been removed from openapi-generator, there's only Dart 2 now

### ISSUE THREAD

**Issue by agilob** [gibahjoe/openapi-generator-dart#31]
Dart 1 support has been removed from openapi-generator, there's only Dart2 now. Generator name `dart` refers to previous dart2. What used to be dart2 is now just `dart`

You can remove `DART2_API` from Generator:

```
enum Generator { DART, DART_DIO, DART2_API, DART_JAGUAR }
```

supportDart2 flag has been removed too

Related:

https://github.com/OpenAPITools/openapi-generator/issues/7561

https://github.com/OpenAPITools/openapi-generator/pull/7568

**Comment by gibahjoe** [comment]
`DART` generator here is actually Dart2 while `DART2_API` is a third party (not produced by the openapi guys) custom generator.

I will need to clean up the naming to avoid confusion in the future.
