### ISSUE TITLE
Problems with the CLI command: console closes with no output

### ISSUE THREAD

**Issue by mattia-venturini** [gibahjoe/openapi-generator-dart#32]
I wanted to use **openapi_generator_cli** (version 2.0.0), so I followed the instructions given on the README.

On Windows, after activating the package using `pub global activate openapi_generator_cli`, the execution of the command `openapi-generator` in the console have some problems: the console closes immadiately without any output. Do you know why?

Another question: why don't you allow to use the command with `pub run`? It would need to rename the _lib/main.dart_ file into _openapi_generator_cli.dart_, so that one could run `pub run openapi_generator_cli <command>` (I tried it out and seemed to work correctly).

**Comment by gibahjoe** [comment]
Hi, thank you for bringing this to my attention. I will take a look at it.

**Comment by gibahjoe** [comment]
Hello @mattia-venturini 

You need to add the directory of your pub cache `flutter/.pub-cache/bin` to your path and then the command will run just fine.

> Another question: why don't you allow to use the command with pub run? It would need to rename the lib/main.dart file into openapi_generator_cli.dart, so that one could run pub run openapi_generator_cli <command> (I tried it out and seemed to work correctly).

If you have already done this, a PR is most welcome.

**Comment by gibahjoe** [comment]
Closing because no clear next steps
