### ISSUE TITLE
Which generator to use?

### ISSUE THREAD

**Issue by mikthemonster** [gibahjoe/openapi-generator-dart#34]
Hi,

I just started using code generation for API in a flutter app. When I look at the different examples I notice different generators:

 - Generator.DART
 - Generator.DART2_API
 - Generator.DART_DIO
 - Generator.DART_JAGUAR

Does anyone know which to use or the difference? Or where to find this information :-)

**Comment by gibahjoe** [comment]
Dart is the regular http that comes with flutter

Jaguar and dio are 3rd party libraries.

I personally use dio because it supports web ( I don't know if Jaguar has added web support)

**Comment by mikthemonster** [comment]
Thanks, I currently use DART.
