### ISSUE TITLE
Use  MultipartFile.fromString to decode binary data

### ISSUE THREAD

**Issue by johngray1965** [gibahjoe/openapi-generator-dart#36]
It looks its very close to handling binary data now, but I still need mess with the code a little.

Namely I'm changing:
attachmentContent: null, // No support for decoding binary content from JSON
to:
MultipartFile.fromString('attachmentContent', json['attachmentContent']);

**Comment by gibahjoe** [comment]
Hi,

You could send a PR to the main openapi generator tool https://github.com/OpenAPITools/openapi-generator.

**Comment by gibahjoe** [comment]
Closing this as this is not an issue with this library but with the openapi tool itself
