### ISSUE TITLE
Generate null-safe code

### ISSUE THREAD

**Issue by ILAgent** [gibahjoe/openapi-generator-dart#41]
I use the latest version (3.0.2) of the generator but generated code is for Dart 2.6 anyway. I expect to have null safe code as a result.

**Comment by gibahjoe** [comment]
Hi, the latest version has null safety for did generator. you can try it out. I haven't used it though

**Comment by Abhilash-Chandran** [comment]
I just upgraded to the new version and still the generated version is non-null safe. I suppose.

```dart
//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//
// @dart=2.7

// ignore_for_file: unused_import
```

I am not sure if I am missing something.

**Comment by Abhilash-Chandran** [comment]
I checked the jar file in the openapi-generator-cli, and it has a folder dart2-v3template which is not present in jar files from the main openapi repository. By any chance are we missing a parameter to be sent so that the generator uses dio version 4.0.0 with null safety..?

**Comment by Abhilash-Chandran** [comment]
I think I found the issue with issue the new dart-dio-next config is missing. I suppose. I used the npm version of the generator with version 5.1.0 with dart-dio-next. It worked ...

**Comment by gibahjoe** [comment]
Hi, thanks for looking into it. Are you saying there is a new generator name to generate bill safe code?

**Comment by Abhilash-Chandran** [comment]
I think so.. Check this https://openapi-generator.tech/docs/generators/dart-dio-next/ out.

**Comment by ILAgent** [comment]
Just forked and checked it out. The value `dart-dio-next` instead of `dart-dio` produces null-safe code!

**Comment by Abhilash-Chandran** [comment]
As per the documentation `dart-dio-next` is still experimental. Perhaps this could also be exposed as an experimental generator.

**Comment by gibahjoe** [comment]
I will add it to a pre-release. thanks

**Comment by malaschitz** [comment]
Because there is still this problem (code is generated with @dart=2.7) I start my app with --no-sound-null-safety option. Is there some another workaround ?

**Comment by StNebel** [comment]
what about the null safety code? Do you have any questions about how it can be installed? @gibahjoe

**Comment by gibahjoe** [comment]
@malaschitz , The dart did next generator was added to the available generators in the last release. From my understanding this generator generates null safe code.

Please try it out.

**Comment by gibahjoe** [comment]
@StNebel Setting the generator property of the config uses the null safe duo generator

```dart
@Openapi(
    additionalProperties:
        AdditionalProperties(pubName: 'petstore_api', pubAuthor: 'Johnny dep'),
    inputSpecFile: 'example/openapi-spec.yaml',
    generatorName: Generator.dioNext,
    outputDirectory: 'api/petstore_api')
```

**Comment by malaschitz** [comment]
@gibahjoe Thanks ! I used `generatorName: Generator.dart` but with `generatorName: Generator.dioNext` is everything all right (but I must rewrote some part of my app). I had some problem with generate code but with this script is everything ok:

```
flutter clean
flutter pub get
flutter pub upgrade
flutter pub run build_runner build --delete-conflicting-outputs --verbose

```

**Comment by alevinetx** [comment]
I ran this with the dart-dio-next, and minus one issue (import on API classes missing ```package:built_value/json_object.dart```), which I haven't opened an issue on yet, all works fine.

However, is built_* the only serialization option available? As nice as immutability is a nice feature, it's a massive pain when passing and manipulating any graph deeper than one level; I think I'm about to cry.   The rewriting everything to extract, rebuild, repackage, from all the prior dart generator contracts... it's not only tedious, it's messy and feels prone to error if the reassignment isn't done in the proper order, etc.

Any suggestions on this?  I really liked the prior serialization, but need the null-safety.

Thank you !

**Comment by mzdm** [comment]
> I ran this with the dart-dio-next, and minus one issue (import on API classes missing `package:built_value/json_object.dart`), which I haven't opened an issue on yet, all works fine.
> 
> However, is built_* the only serialization option available? As nice as immutability is a nice feature, it's a massive pain when passing and manipulating any graph deeper than one level; I think I'm about to cry. The rewriting everything to extract, rebuild, repackage, from all the prior dart generator contracts... it's not only tedious, it's messy and feels prone to error if the reassignment isn't done in the proper order, etc.
> 
> Any suggestions on this? I really liked the prior serialization, but need the null-safety.
> 
> Thank you !

I like this one https://github.com/epam-cross-platform-lab/swagger-dart-code-generator (the only downside is that it does not support all types, such as Uint8List https://github.com/epam-cross-platform-lab/swagger-dart-code-generator/issues/116) but it is maintainted

**Comment by alevinetx** [comment]
thanks for that recommendation, @mzdm !  

I think I may look at just updating the ```dart``` generator templates to add a ? to all the var types, etc.  This may be the quickest path over updating way too many object manipulations.

**Comment by gibahjoe** [comment]
closing this. Please feel free to reopen

**Comment by rockgecko-development** [comment]
Hi @alevinetx , I have added the option to generate mutable models in the `epam-cross-platform-lab/swagger-dart-code-generator` project, in this PR if you'd like to take a look or weigh in: https://github.com/epam-cross-platform-lab/swagger-dart-code-generator/pull/247
