### ISSUE TITLE
AnyOf and OneOf methods are not generated in 3.1.2

### ISSUE THREAD

**Issue by vladaman** [gibahjoe/openapi-generator-dart#43]
Generator version 3.1.2 generates source code but OpenAPI features such as anyOf or allOf don't get generated

Yaml:
```yaml
        widgets:
          type: array
          items:
            anyOf:
            - $ref: '#/components/schemas/CarouselWidget'
            - $ref: '#/components/schemas/RowItemsWidget'
            - $ref: '#/components/schemas/CardWidget'
            - $ref: '#/components/schemas/TextWidget'
      CarouselWidget:
      type: object
      description: "CarouselWidget View Widget wrapps multiple widegets Carrousel"
      allOf:
        - $ref: '#/components/schemas/ClickableWidget'
      properties:
        widgets:
          type: array
          items:
            $ref: '#/components/schemas/CardWidget'
```

![Screenshot from 2021-04-21 11-22-26](https://user-images.githubusercontent.com/907206/115530301-ecb35500-a293-11eb-8751-fe4d839fc705.png)

**Comment by abianche** [comment]
@vladaman did you actually find a way to resolve this? I think that's because of Dart which doesn't support type unions. Or was such a function generated in previous versions?

**Comment by gibahjoe** [comment]
Hi, as @abianche said, dart does not support type unions unfortunately. So the way to go in this case will be to use `dynamic` or `object` instead.

**Comment by abianche** [comment]
> Hi, as @abianche said, dart does not support type unions unfortunately. So the way to go in this case will be to use `dynamic` or `object` instead.

Is this something where a PR would make sense. Getting rid of all AnyOf and similar, and replace them with dynamic basically?
Would it be possible to then infer the type, using "value is MyClass" statements?

**Comment by gibahjoe** [comment]
Sorry, I haven't had time to follow up on this.

Although I haven't tested myself, I think the latest versions of the library now support AnyOf types. You can check them out

But in the case they don't, You can use the typeMappings field of to change the types to dynamic.


in your case, it will be like below

```dart
@Openapi(
    additionalProperties: AdditionalProperties(
        pubName: 'petstore_api',
        pubAuthor: 'Johnny dep.'),
    inputSpecFile: 'openapi-spec.yaml',
    typeMappings: {
      'AnyOfCarouselWidgetCardWidgetTextWidget': 'dynamic' // add this
    },
    generatorName: Generator.dioNext,
    outputDirectory: 'api/petstore_api')
```

I am closing this now, anybody feel free to open if issues persist.
