### ISSUE TITLE
Support build versions above 2.0.0

### ISSUE THREAD

**Issue by atoka93** [gibahjoe/openapi-generator-dart#47]
The latest version of the `build` package is `2.0.1`.
Another package that I am using is relying on it already which makes it incompatible  with `openapi_generator`.

If it's possible and not too much trouble it would be great if you could increase the limit.

**Comment by gibahjoe** [comment]
Updated in release 3.1.3

**Comment by atoka93** [comment]
Great, thanks! 😃
