### ISSUE TITLE
Could not find package "build_runner". Did you forget to add a dependency?

### ISSUE THREAD

**Issue by kishoresahas** [gibahjoe/openapi-generator-dart#49]
When am running the below,
`flutter pub run build_runner build --delete-conflicting-outputs`

![image](https://user-images.githubusercontent.com/5591712/119228987-5644ae80-bb33-11eb-8e80-8711483e9a1c.png)

Does this require build_runner to be added to `.\openapi-generator-dart\openapi-generator\pubspec.yaml` or `.\openapi-generator-dart\openapi-generator\example\pubspec.yaml`

**Comment by gibahjoe** [comment]
Hi. You need to add build runner to your dependencies in your project because the command flutter pub run build_runner build --delete-conflicting-outputs uses that.

**Comment by TamasBarta** [comment]
I think it would be helpful if it was documented in the getting started examples.

**Comment by Liniik** [comment]
Why it isn't in the readme or mentioned in "depends on"?
