### ISSUE TITLE
Cannot upgrade app to http 0.13.3 due to outdated `dio` and `openapi_dart_common` generated dependencies and incompatible generated API

### ISSUE THREAD

**Issue by jbx1** [gibahjoe/openapi-generator-dart#50]
When trying to use in an app that needs to use the latest `http ^0.13.3` this generator does not work. 

```
Because no versions of http match >0.13.3 <0.14.0 and http 0.13.3 depends on http_parser ^4.0.0, http ^0.13.3 requires http_parser ^4.0.0.
And because every version of api from path depends on dio ^3.0.10 which depends on http_parser >=0.0.1 <4.0.0, http ^0.13.3 is incompatible with api from path.
So, because App depends on both api from path and http ^0.13.3, version solving failed.
pub get failed (1; So, because App depends on both api from path and http ^0.13.3, version solving failed.)
```

The problem is not just with upgrading the generated `pubspec.yaml`. 

When one tries to upgrade `dio` manually to 4.0.0, because then the following problem occurs:

```
Because openapi_dart_common >=3.2.0 <4.0.0-prev1 depends on dio ^3.0.10 and api depends on dio >=4.0.0, openapi_dart_common >=3.2.0 <4.0.0-prev1 is forbidden.
So, because api depends on openapi_dart_common ^3.2.0, version solving failed.
```

The latest version of openapi_dart_common is actually 4.1.0  which solves the `pub get` issue. 

But then, the generated API files are not compatible any more because the function `decodeBodyBytes(ApiResponse response)` changed to `decodeBodyBytes(Stream<List<int>> body)` in `openapi_dart_common`. (It is expecting the `response.body` instead of the `response`).

**Comment by malaschitz** [comment]
My workarounds for http 0.13.3 is change `uri,` to `Uri.parse(uri),` in generated api_client.dart 
I have it in my shell script with command `sed`.

**Comment by jbx1** [comment]
I don't think my problem is the same, because I am using dioAlt generator. I could fix these errors and change the call to use `response.body` in the generated code but then regenerating the first would just overwrite these changes. 

Having a look at the `ogurets` code, it seems something to do with nullsafe because the template is selecting dio 4.0.0 and openapi_dart_common 4.1.0 in case of nullsafe. 

https://github.com/dart-ogurets/dart-openapi-maven/blob/master/src/main/resources/dart2-v3template/pubspec.mustache

Not sure how to specify this nullsafe in the generator configuration.

**Comment by StNebel** [comment]
@gibahjoe can you upgrade dep to latestest version? s.b. need it + me. thx

**Comment by gibahjoe** [comment]
@jbx1 You can try using various dependency_overides to get around the original issue.

**Comment by gibahjoe** [comment]
@StNebel I will upgrade the versions and publish soon

**Comment by jbx1** [comment]
To be able to use http 0.13.3 and the other dependencies in a more recent version, I need the generator to generate code and pubspec.yaml that uses the newer version. The dioAlt generator (dart-ogurets dart2-api) actually has a flag, `nullSafe`, that when set it will use the most recent versions of the libraries in its pubspec.yaml and generate code that is nullsafe. It also has another one about nullsafe arrays, which goes hand in hand with it. You can't just override the dependencies, code generation will be wrong. 

But the current version of this openapi-generator doesn't support setting these 2 flags.

My workaround for now is to use the openapi-generator-cli and run that instead of this. Generating them from CLI generates the  right files with up to date dependencies.

**Comment by gibahjoe** [comment]
Do you have a link to where this is documented so that I can read more about it and update the library soonest?

**Comment by jbx1** [comment]
Yes, the properties are mentioned here: https://github.com/dart-ogurets/dart-openapi-maven

If you look here in their code, you will see that when `nullSafe` is turned on, they generate the pubspec.yaml with  `dio: '^4.0.0'` and `openapi_dart_common: ^4.1.0`  while when it is not it generates it with ` dio: '>=3.0.10 <4.0.0'` and  `openapi_dart_common: ^3.2.0` which then conflicts with the other dependencies like `http`.

https://github.com/dart-ogurets/dart-openapi-maven/blob/master/src/main/resources/dart2-v3template/pubspec.mustache

So if this file had an additional `DioAltAdditionalProperties` for the `dioAlt` generator just like the ones for Jaguar etc., we would be able to pass the `nullSafe` and `nullSafe-array-default` :

https://github.com/gibahjoe/openapi-generator-dart/blob/master/openapi-generator-annotations/lib/src/openapi_generator_annotations_base.dart

If these are then passed to the generator the code would then be compatible with the latest dependency versions (and null-safe).

**Comment by gibahjoe** [comment]
- `nullSafe` flag added to `DioAltProperties`
- `nullSafe-array-default` added to `DioAltProperties`
- Added dionext generator
- Bumped `dioAlt` version to 5.9
