### ISSUE TITLE
Could it be possible to have full project example ?

### ISSUE THREAD

**Issue by FlorianArnould** [gibahjoe/openapi-generator-dart#51]
Hi, thank for your work.
I'm coming from  the web dev and I'm developping a flutter which will integrate an existing ecosystem with a react.js frontend and a ASP.NET backend.
On this project, we use the **API First development** flow, so the openapi spec is designed at first and the code is generated on each side using generators (NSwag for ASP.NET, OpenApi generator cli for React and this project for the coming flutter app).
Usually the generator, generate file (Nswag), a module (Angular), or a project (java spring). But all of them are easily imported in the existing project to be used as an external lib. Also I **never track the generated sources in the git repo**. It's always **generated during the build process** to be sure all the code is ok and not manually modified. 
Here, I don't get how you intended this to be used, but maybe it's coming from me as I'm quite new to flutter and the build_runner thing. So a full example could be useful instead of just having some pieces of config and code.

After all, I will try to explain what I trying to do and maybe you will be able to help me.
So I have an `openapi.yml` file in my existing flutter project and I would like to generate the dart services to get the ability to call the backend without implementing these by myself. 
So I  added `openapi_generator_annotations: ^3.1.2` and  `openapi_generator: ^3.1.2` to my project `dependencies` and `dev_dependencies`. (`build_runner: ^1.12.2` too)
I created a file `lib/configuration/application_api_config.dart` containing:
```dart
import 'package:openapi_generator_annotations/openapi_generator_annotations.dart';

@Openapi(
    additionalProperties: AdditionalProperties(
        pubName: "application_api"
    ),
    inputSpecFile: 'path/to/my/openapi.yml',
    generatorName: Generator.dioNext,
    outputDirectory: 'api/application'
)
class ApplicationApiConfig extends OpenapiGeneratorConfig {}
```
So when I run `flutter pub run build_runner build --delete-conflicting-outputs` it generates a side project in `api/application` that I need to import in my main project to use it. So I added this to my pubspec.yaml: 
```yml
application_api:
    path: ./api/application
```
but here it creates a dependency loop. When I clone the repo without the generated sources the `flutter pub get` fails because the missing `application_api` dependency but I need to get the other dependencies to generate these sources.

I don't know if all of this is clear. But I would like to have some help from someone used to these dart lib to advice me on this.
Thank in advance !

**Comment by gibahjoe** [comment]
Hi.
The way around this is that you need to commit just the `pubspec.yaml `of your api project to the repo.

That way, anyone who pulls the code pulls it to and you can run `pub get` before generating the api project.

**Comment by gibahjoe** [comment]
Fell free to open this issue if you have further questions
