### ISSUE TITLE
Feature Request: info version

### ISSUE THREAD

**Issue by mars3142** [gibahjoe/openapi-generator-dart#55]
My OpenAPI json does include a property **info->version**. 

Is it possible to expose the info data within the generated classes? I need it to send it to my backend for frontend, so we can create a versioned API.

I would like to create a PR, if someone point me into the right direction, where I can add this.

**Comment by gibahjoe** [comment]
Hi, could you please elaborate on this?

**Comment by mars3142** [comment]
We generate with OpenAPI a JSON and this is converted into dart classes. Within the JSON we see a property "version", which can be set by the JSON creators. But I can't find any reference to this field within the dart code. That's why I asked, if it's possible to generate an info object with that version (and other data).

**Comment by gibahjoe** [comment]
Hi, Please raise feature requests with the original author of the generator [here](https://github.com/OpenAPITools/openapi-generator/issues/new/choose)
