### ISSUE TITLE
Generator not working on Windows platform

### ISSUE THREAD

**Issue by andrijailic** [gibahjoe/openapi-generator-dart#6]
When i start generator as described in documentation i get:

```
[WARNING] openapi_generator:openapi_generator on lib/api/ApiGenerator.dart:
Error: Unable to access jarfile /D:/mobile/flutter_windows/flutter/.pub-cache/hosted/pub.dartlang.org/openapi_generator_cli-1.0.5/lib/openapi-generator.jar

[WARNING] openapi_generator:openapi_generator on lib/api/ApiGenerator.dart:
openapi:generate exited with code 1
```

Seems like "${"${binPath.path}"}" in openapi_generator_runner.dart generates wrong jar path on Windows platform.

My observation may be wrong since i am really new to Flutter and Dart, but when i manually compose all outputs from plugin, and remove leading "/" in jar path and run it in terminal - all seems to work just fine.

**Comment by gibahjoe** [comment]
Hello @andrijailic ,

Thank you for opening this issue. 

I will look into it.

Thanks once again

**Comment by gibahjoe** [comment]
Hi @andrijailic 

A fix has been published.

Check pub.dev for the latest version (1.0.8) and check if its fine now.

Thanks

**Comment by gibahjoe** [comment]
Closing this for now. Dont hesitate to open again if its not resolved

**Comment by andrijailic** [comment]
It works now, thanks :)
