### ISSUE TITLE
Object as query parameter

### ISSUE THREAD

**Issue by jpunz** [gibahjoe/openapi-generator-dart#62]
Hi,

just found an issue when using an Object as Query-Parameter.
When using e.g. swagger-codegen (Java), it's possible to do the following:

```
/xyz:
    get:
      parameters:
      - in: query
        required: false
        name: someBoolean
        schema:
          type: boolean
      - in: query
        name: someObject
        required: false
        schema:
          $ref: '#/components/schemas/SomeObjectDto'
```

In this case e.g. Swagger uses all properties of SomeObjectDto as Query Parameter.

In your lib the toString-Method of each Object is used as query parameter. E.g.:
```
@override
String toString() => 'SomeObjectDto[propA=$propA, propB=$propB]';
```

I think this should get corrected :)

Regards,
Jürgen

**Comment by gibahjoe** [comment]
Hi @jpunz , Thank you for reaching out. However, this library is a wrapper around the dart implementation of the generator by [OpenApiTools](https://github.com/OpenAPITools/openapi-generator). You can raise with them [here](https://github.com/OpenAPITools/openapi-generator/issues/new/choose) for better support.
