### ISSUE TITLE
AnyOf doesn't code generate correctly.

### ISSUE THREAD

**Issue by domesticmouse** [gibahjoe/openapi-generator-dart#69]
I have a OpenAPI spec that includes the following component that confuses the `openapi_generator` to no end:

```json
"ValidationError": {
    "title": "ValidationError",
    "required": [
        "loc",
        "msg",
        "type"
    ],
    "type": "object",
    "properties": {
        "loc": {
            "title": "Location",
            "type": "array",
            "items": {
                "anyOf": [
                    {
                        "type": "string"
                    },
                    {
                        "type": "integer"
                    }
                ]
            }
        },
        "msg": {
            "title": "Message",
            "type": "string"
        },
        "type": {
            "title": "Error Type",
            "type": "string"
        }
    }
}
```

This winds up with a `AnyOfstringinteger` which isn't generated.

**Comment by domesticmouse** [comment]
The source of this appears to be: https://github.com/tiangolo/fastapi/pull/4806

**Comment by gboscaro-imtech** [comment]
I have the same problem. Any idea on how to fix this? I can do it manually as a temporary fix but I would like to have an example of how the code should look like.

**Comment by szekelyisz** [comment]
To me it looks like the OpenAPI Dart generator doesn't support anyOf: https://openapi-generator.tech/docs/generators/dart#schema-support-feature

As such, this is not an issue with this repo, but rather https://github.com/OpenAPITools/openapi-generator

**Comment by gibahjoe** [comment]
I know it has been a while but in case anyone else stumbles on this, `Anyof` support has been added to the `dio` generator.
