### ISSUE TITLE
Can this library used to generate model classes from swagger.json 

### ISSUE THREAD

**Issue by sherifhasan** [gibahjoe/openapi-generator-dart#7]

**Comment by gibahjoe** [comment]
While this library has not been tested with Swagger v.2.0, I believe it should work out of the box. However, if you are having trouble with it, for more compatibility, you might want to convert your v2 spec file to OpenApi v3. You can try this website to help do that https://openapi-converter.herokuapp.com/

Let me know if you need further assistance
