### ISSUE TITLE
Dio client version is still <5.0.0

### ISSUE THREAD

**Issue by giovannilattanziocrispy** [gibahjoe/openapi-generator-dart#89]
### Description of the bug

The package still uses a Dio client < 5.x.x (`dio: '>=4.0.1 <5.0.0'`).

### Steps to reproduce

Using the openapi_generator_annotations 4.10.0 we should be able to create Dio client with version > 5.x.x because the openapi generator is bumped to 6.4.0 (see changelog [https://github.com/OpenAPITools/openapi-generator/releases/tag/v6.4.0](url)).

### Expected behavior

The package should be updated to create a Dio client with the 5.x.x version.

### Platform

Linux

### Library version

4.10.0

### Flutter version

3.7.11

### Flutter channel

stable

**Comment by gibahjoe** [comment]
No longer the case as at 4.12.0
