### ISSUE TITLE
App Store Connect Api has a lot of syntax bugs

### ISSUE THREAD

**Issue by long1eu** [gibahjoe/openapi-generator-dart#9]
Hi!

I tried to build the App Store Connect Api but the are some issues with the syntax that gets generated.
Can you have a look?

[app-store-connect-openapi-spec.json.zip](https://github.com/gibahjoe/openapi-generator-dart/files/4901795/app-store-connect-openapi-spec.json.zip)

**Comment by gibahjoe** [comment]
Hello @long1eu ,

thanks for reaching out. Please provide more information on the syntax issues you encountered.

Also, the spec you provided is not valid and has some errors.
Try to validate it on https://editor.swagger.io/ 

Let me know if you need further assistance.

**Comment by long1eu** [comment]
I understand. The spec is from Apple.
https://developer.apple.com/sample-code/app-store-connect/app-store-connect-openapi-specification.zip

**Comment by long1eu** [comment]
thanks for your work

**Comment by gibahjoe** [comment]
No problem
