### ISSUE TITLE
Generator Should always run if alwaysRun flag is set

### ISSUE THREAD

**Issue by Nexushunter** [gibahjoe/openapi-generator-dart#95]
### Description of the bug

The current implementation forces either an update to the `outputDirectory` or delete the current `outputDirectory`. This prevents incremental updates an retaining the current testing being given to the generated clients / servers.

### Steps to reproduce

make a change to the open api spec. ie add a content type to the response.
run `dart run build_runner build --delete-conflicting-outputs`

### Expected behavior

Regenerates new changes in `outputDirectory`

### Logs

```text
dart run build_runner build --delete-conflicting-outputs
[INFO] Generating build script completed, took 227ms
[INFO] Reading cached asset graph completed, took 39ms
[INFO] Checking for updates since last build completed, took 324ms
[INFO] Running build completed, took 10ms
[INFO] Caching finalized dependency graph completed, took 22ms
[INFO] Succeeded after 37ms with 0 outputs (0 actions)
```

### Platform

Linux

### Library version

4.11.0

### Flutter version

3.0.5 - Dart

### Flutter channel

stable

**Comment by gibahjoe** [comment]
Hi, can you please explain the issue? What behavior are you expecting? Are you saying the output directory is not updated when you run the generator?

**Comment by Nexushunter** [comment]
👋🏻 Hi! Yep that is correct. When I making a change to the OAS spec and rerun the generator the output directory doesn't get updated as I would expect it to even when the `alwaysRun` flag is set. 

As a work around I either need to update the path for the output directory or I can remove the `.dart_tool` directory (this has an additional burden of having to constantly redownload the dependencies). Both of these cause the generator to update the output directory as expected.

The note about the process being skipped if the output directory exists sticks out as a cause of the issue. The generation should still run in the event that the directory exists.

![image](https://github.com/gibahjoe/openapi-generator-dart/assets/29546913/c9a50e6e-a69b-47c0-8ae4-69af3eda68fb)

**Comment by gibahjoe** [comment]
For the generator to run again, you need to make a change to the file that has your ```@openapi``` annotation. This is because the generator uses build runner and build runner only runs on files that have changed.

Something I do is just add a full stop behind the pubDescription or pubAuthor for instance.

So, in your case, make a change to the ```tagmine_api.dart``` file before running ```build runner``` command.

Let me know if this helps or if I have addressed your issue.

**Comment by gibahjoe** [comment]
Of course. This will be a very welcome update. Thank you.

**Comment by gibahjoe** [comment]
(4.12.0)[https://pub.dev/packages/openapi_generator] has been pushed. Thanks once again
