### ISSUE TITLE
Invalid timezone parsed from server response

### ISSUE THREAD

**Issue by ricardoboss** [gibahjoe/openapi-generator-dart#97]
### Description of the bug

My API returns timestamps in UTC, but the generated API client parses them with the local timezone, which is wrong.

### Steps to reproduce

1. Create an API that returns the current timestamp in UTC. E.g. using ASP.NET.
2. Create a dart project and generate an API client
3. Consume the endpoint returning the current timestamp

### Expected behavior

The endpoint returns something like `2023-08-18T21:14:00.3956592` and the parsed Dart `DateTime` object should parse this value as being UTC.

### Platform

Windows

### Library version

4.11.0

### Flutter version

3.13

### Flutter channel

stable

**Comment by gibahjoe** [comment]
That is not UTC time because it does not contain timezone information. UTC time will be ```2023-08-20T04:16:08**+0000**```.

The issue is that because there is no timezone information in the time string (UTC should have +0000 for it to be UTC), dart assumes that it is local time. Then during deserialization, BuiltValue converts it to UTC

You can declare a custom Serializer plugin for DateTime to implement custom behaviour. 

This is an example

```dart
var customSerializer = (serializers.toBuilder()
      ..add(NigeriaIso8601DateTimeSerializer())
      ..addPlugin(StandardJsonPlugin()))
    .build();
    
    class NigeriaIso8601DateTimeSerializer
    implements PrimitiveSerializer<DateTime> {
  final bool structured = false;
  @override
  final Iterable<Type> types = BuiltList<Type>([DateTime]);
  @override
  final String wireName = 'DateTime';

  @override
  Object serialize(Serializers serializers, DateTime dateTime,
      {FullType specifiedType = FullType.unspecified}) {
    return dateTime.toIso8601String();
  }

  @override
  DateTime deserialize(Serializers serializers, Object? serialized,
      {FullType specifiedType = FullType.unspecified}) {
    return DateTime.parse('$serialized+0000' as String).toUtc();
  }
}
```

then use it like this


```dart
var appApi = MyApi(
  dio: Dio(options),
  **serializers: customSerializer,**
  interceptors: [],
);
```

**Comment by ricardoboss** [comment]
I understand. Thanks for the insight! I decided to fix this in my API though, so for ASP.NET, I added a custom `DateTime` converter, that always includes the time zone:

```csharp
public class DateTimeConverterIncludingTimeZone : JsonConverter<DateTime>
{
    public override DateTime Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        Debug.Assert(typeToConvert == typeof(DateTime));

        return DateTime.Parse(reader.GetString() ?? string.Empty);
    }

    public override void Write(Utf8JsonWriter writer, DateTime value, JsonSerializerOptions options)
    {
        writer.WriteStringValue(value.ToString("yyyy-MM-ddTHH:mm:ss.fffzzz"));
    }
}
```

In `Program.cs`:

```csharp
    builder.Services.AddControllers()
        .AddJsonOptions(o =>
        {
            o.JsonSerializerOptions.Converters.Add(new DateTimeConverterIncludingTimeZone());
        });
```

Now my API includes a `Z` for UTC in timestamps.

I'll close this issue, as either solution (yours on the Dart side or mine on the API side) should fix the problem.
